### ISSUE TITLE
伸缩

### ISSUE THREAD

**Issue by weijunyan1** [FullStack-2019/WeiJunYan#1]

**Comment by wanlum** [comment]
你在说啥呢我看到了

**Comment by TAC-5** [comment]
没有，我昨天试了一下，我怕我操作不对，所以交了一版。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YeungWanLum"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 下午5:15
收件人: "FullStack-2019/WeiJunYan"<WeiJunYan@noreply.github.com&gt;; 
抄送: "闲者^O^&amp;"<3467913546@qq.com&gt;; "Assign"<assign@noreply.github.com&gt;; 
主题: Re: [FullStack-2019/WeiJunYan] 伸缩 (#1)




你在说啥呢我看到了
